/* AUTO-GENERATED by tools/generate_manifest.py — do not edit. */
window.DASHBOARD_MANIFEST = {
  "project": {
    "title": "Intelligent Coordinated EV Charging Strategy",
    "subtitle": "Voltage and Thermal Stability in Weak Distribution Grids with High PV Penetration",
    "author": "Final Year Project · University of Moratuwa",
    "thesis": "A two-layer PSO + Fuzzy controller staggers EV charging across a weak, high-PV IEEE 33-bus grid — keeping every bus voltage in band and the transformer under its rating, while delivering essentially the same EV energy as the uncoordinated baseline."
  },
  "generated_from": "Dashboard/",
  "sections": [
    {
      "id": "1-domestic-load-and-pv-profiles",
      "order": 1.0,
      "title": "Domestic load and PV profiles",
      "display": "figures",
      "figures": [
        {
          "src": "assets/01-domestic-load-and-pv-profiles/01-domestic-load-profile.png",
          "title": "Domestic Load profile",
          "caption": "Per-unit domestic demand across the 24-hour day.",
          "description": "A small overnight base, a modest morning bump around 07:00, and the dominant evening peak near 18:00–19:00 — the window the EV load later collides with."
        },
        {
          "src": "assets/01-domestic-load-and-pv-profiles/02-pv-profile-without-intermitency.png",
          "title": "PV profile without intermitency",
          "caption": "Clear-sky PV generation profile (per unit).",
          "description": "A smooth bell shape rising from ~06:00, peaking at midday, and falling by ~18:00. This is the ideal-day reference before clouds are introduced."
        },
        {
          "src": "assets/01-domestic-load-and-pv-profiles/03-pv-profile-with-intermitency.png",
          "title": "PV profile with intermitency",
          "caption": "PV generation with cloud-induced intermittency.",
          "description": "The same midday envelope, now jagged with rapid dips as passing clouds shade the array. This fast variability is what induces voltage flicker on a weak grid and what the controller's fluctuation term must damp."
        }
      ],
      "children": [],
      "blocks": [],
      "intro": "Daily per-unit profiles that drive the simulation: domestic demand and PV generation (smooth, then with cloud-induced intermittency)."
    },
    {
      "id": "2-ev-profile-and-occupancies",
      "order": 2.0,
      "title": "EV profile and occupancies",
      "display": "figures",
      "figures": [
        {
          "src": "assets/02-ev-profile-and-occupancies/01-sample-ev-profile-data-collected.png",
          "title": "Sample EV profile data collected",
          "caption": "Sample of the per-EV input data.",
          "description": "Each EV is described by arrival/departure times, arrival and target SOC, battery capacity, and the resulting energy request (kWh). These rows feed the EV_Data spreadsheets used by both scenarios."
        },
        {
          "src": "assets/02-ev-profile-and-occupancies/02-energy-requested-equation.png",
          "title": "Energy requested equation",
          "caption": "Energy-request formula.",
          "description": "Required energy = (battery capacity ÷ charging efficiency) × (target SOC − arrival SOC) ÷ 100. This sets how much each EV must receive before it departs."
        },
        {
          "src": "assets/02-ev-profile-and-occupancies/03-ev-occupancy-1.png",
          "title": "EV occupancy 1",
          "caption": "EV aggregation occupancy — sample 1.",
          "description": "Number of vehicles present at a station through the day: filling from morning arrivals, a midday dip as some depart, then refilling toward evening."
        },
        {
          "src": "assets/02-ev-profile-and-occupancies/04-ev-occupancy-2.png",
          "title": "EV occupancy 2",
          "caption": "EV aggregation occupancy — sample 2.",
          "description": "A second station's occupancy pattern, showing the stochastic spread of arrivals and departures across the modelled fleet."
        },
        {
          "src": "assets/02-ev-profile-and-occupancies/05-ev-occupancy-3.png",
          "title": "EV occupancy 3",
          "caption": "EV aggregation occupancy — sample 3.",
          "description": "A third occupancy realisation — together these illustrate the time-varying, up-to-40-vehicle population each aggregation must serve."
        }
      ],
      "children": [],
      "blocks": [],
      "intro": "How the EV charging population is modelled — sample arrival/departure/SOC data, the energy-request formula, and resulting station occupancy."
    },
    {
      "id": "3-weak-distribution-grid-test-system",
      "order": 3.0,
      "title": "Weak distribution grid test system",
      "display": "figures",
      "figures": [
        {
          "src": "assets/03-weak-distribution-grid-test-system/01-ieee-33-bus-network.png",
          "title": "Ieee 33 bus network",
          "caption": "Modified IEEE 33-bus radial distribution feeder.",
          "description": "Single substation (slack) feeding 33 buses radially at 11 kV. Five EV charging aggregations (buses 6, 14, 20, 23, 26) and five 1 MWp PV sites are added to the standard benchmark. Domestic loads are scaled ×2.1 to make the grid 'weak'."
        }
      ],
      "children": [],
      "blocks": [
        {
          "type": "info",
          "groups": [
            {
              "heading": "11 kV Distribution Network",
              "pairs": [
                {
                  "label": "Transformer rating",
                  "value": "10 MVA"
                }
              ]
            },
            {
              "heading": "Cable – 360 mm² AAAC",
              "pairs": [
                {
                  "label": "Ampacity",
                  "value": "525 A"
                },
                {
                  "label": "Domestic Load",
                  "value": "9.18 MVA"
                }
              ]
            },
            {
              "heading": "0.85 p.f.",
              "pairs": [
                {
                  "label": "Total PV Capacity",
                  "value": "5 MWp"
                }
              ]
            }
          ],
          "lines": [
            "Backward - Forward Sweep Loadflow analysis",
            "50 % Penetration",
            "40 EVs per aggregation",
            "11 kW chargers",
            "5 Aggregations",
            "22 % penetration"
          ]
        }
      ],
      "intro": "The modified IEEE 33-bus radial feeder used as the test system, deliberately made 'weak' so EV and PV stress is clearly visible."
    },
    {
      "id": "4-uncoordinated-ev-charging",
      "order": 4.0,
      "title": "Uncoordinated EV Charging",
      "display": "figures",
      "figures": [
        {
          "src": "assets/04-uncoordinated-ev-charging/bus-5-and-18-voltage-comparison.png",
          "title": "Bus 5 and 18 voltage comparison",
          "caption": "Voltage at bus 5 vs bus 18 (uncoordinated).",
          "description": "A near-substation bus (5) stays comfortably in band, while the far-end bus (18) sags hardest at the evening peak — the clearest single view of where the weak grid fails first."
        }
      ],
      "children": [
        {
          "id": "4-uncoordinated-ev-charging-1-voltage-profile-of-33-buses",
          "order": 1.0,
          "title": "Voltage profile of 33 buses",
          "display": "gallery",
          "figures": [
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-1.png",
              "title": "Bus 1",
              "caption": "Bus 1 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 1 against the 0.94 pu lower limit. Near the substation, voltage stays close to nominal."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-2.png",
              "title": "Bus 2",
              "caption": "Bus 2 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 2 against the 0.94 pu lower limit. Near the substation, voltage stays close to nominal."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-3.png",
              "title": "Bus 3",
              "caption": "Bus 3 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 3 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-4.png",
              "title": "Bus 4",
              "caption": "Bus 4 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 4 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-5.png",
              "title": "Bus 5",
              "caption": "Bus 5 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 5 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-6.png",
              "title": "Bus 6",
              "caption": "Bus 6 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 6 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-7.png",
              "title": "Bus 7",
              "caption": "Bus 7 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 7 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-8.png",
              "title": "Bus 8",
              "caption": "Bus 8 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 8 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-9.png",
              "title": "Bus 9",
              "caption": "Bus 9 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 9 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-10.png",
              "title": "Bus 10",
              "caption": "Bus 10 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 10 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-11.png",
              "title": "Bus 11",
              "caption": "Bus 11 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 11 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-12.png",
              "title": "Bus 12",
              "caption": "Bus 12 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 12 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-13.png",
              "title": "Bus 13",
              "caption": "Bus 13 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 13 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-14.png",
              "title": "Bus 14",
              "caption": "Bus 14 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 14 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-15.png",
              "title": "Bus 15",
              "caption": "Bus 15 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 15 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-16.png",
              "title": "Bus 16",
              "caption": "Bus 16 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 16 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-17.png",
              "title": "Bus 17",
              "caption": "Bus 17 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 17 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-18.png",
              "title": "Bus 18",
              "caption": "Bus 18 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 18 against the 0.94 pu lower limit. Bus 18 is the critical far-end bus where the deepest sag occurs."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-19.png",
              "title": "Bus 19",
              "caption": "Bus 19 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 19 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-20.png",
              "title": "Bus 20",
              "caption": "Bus 20 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 20 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-21.png",
              "title": "Bus 21",
              "caption": "Bus 21 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 21 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-22.png",
              "title": "Bus 22",
              "caption": "Bus 22 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 22 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-23.png",
              "title": "Bus 23",
              "caption": "Bus 23 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 23 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-24.png",
              "title": "Bus 24",
              "caption": "Bus 24 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 24 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-25.png",
              "title": "Bus 25",
              "caption": "Bus 25 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 25 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-26.png",
              "title": "Bus 26",
              "caption": "Bus 26 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 26 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-27.png",
              "title": "Bus 27",
              "caption": "Bus 27 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 27 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-28.png",
              "title": "Bus 28",
              "caption": "Bus 28 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 28 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-29.png",
              "title": "Bus 29",
              "caption": "Bus 29 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 29 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-30.png",
              "title": "Bus 30",
              "caption": "Bus 30 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 30 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-31.png",
              "title": "Bus 31",
              "caption": "Bus 31 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 31 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-32.png",
              "title": "Bus 32",
              "caption": "Bus 32 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 32 against the 0.94 pu lower limit."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/01-voltage-profile-of-33-buses/bus-33.png",
              "title": "Bus 33",
              "caption": "Bus 33 voltage over 24 hours (coordinated).",
              "description": "Per-unit voltage trajectory at bus 33 against the 0.94 pu lower limit."
            }
          ],
          "children": [],
          "blocks": []
        },
        {
          "id": "4-uncoordinated-ev-charging-2-transformer-and-line-loading",
          "order": 2.0,
          "title": "Transformer and line loading",
          "display": "figures",
          "figures": [
            {
              "src": "assets/04-uncoordinated-ev-charging/02-transformer-and-line-loading/01-transformer-loading.png",
              "title": "Transformer loading",
              "caption": "Transformer apparent power vs the 10 MVA rating (uncoordinated).",
              "description": "Loading climbs through the evening and breaches the 10 MVA limit at the peak (shaded overload region) — a thermal violation of the distribution transformer."
            },
            {
              "src": "assets/04-uncoordinated-ev-charging/02-transformer-and-line-loading/02-main-feeder-line-loading.png",
              "title": "Main feeder line loading",
              "caption": "Main feeder current vs the 525 A ampacity (uncoordinated).",
              "description": "Current on the main feeder during the night peak, checked against the 360 mm² AAAC cable ampacity of 525 A."
            }
          ],
          "children": [],
          "blocks": []
        },
        {
          "id": "4-uncoordinated-ev-charging-3-ev-charging",
          "order": 3.0,
          "title": "EV charging",
          "display": "tabs",
          "figures": [],
          "children": [
            {
              "id": "4-uncoordinated-ev-charging-3-ev-charging-station-1-bus-6",
              "order": 10000.0,
              "title": "Station 1 - bus 6",
              "display": "figures",
              "figures": [
                {
                  "src": "assets/04-uncoordinated-ev-charging/03-ev-charging/station-1-bus-6/01-ev-charging-schedule-bus-6.png",
                  "title": "EV Charging schedule bus 6",
                  "caption": "EV Charging schedule bus 6 (coordinated).",
                  "description": "Per-EV status grid (absent / charging / connected-not-charging / fully charged) over the day. Charging is staggered so the grid stays in limits while every EV still finishes."
                },
                {
                  "src": "assets/04-uncoordinated-ev-charging/03-ev-charging/station-1-bus-6/no-of-evs-charging-station-1-bus-6.png",
                  "title": "No. of EVs Charging - Station 1 (Bus 6)",
                  "caption": "No. of EVs Charging - Station 1 (Bus 6).",
                  "description": "Count of simultaneously charging EVs at this station through the day."
                }
              ],
              "children": [],
              "blocks": []
            },
            {
              "id": "4-uncoordinated-ev-charging-3-ev-charging-station-2-bus-14",
              "order": 10000.0,
              "title": "Station 2 - bus 14",
              "display": "figures",
              "figures": [
                {
                  "src": "assets/04-uncoordinated-ev-charging/03-ev-charging/station-2-bus-14/02-ev-charging-schedule-bus-14.png",
                  "title": "EV Charging schedule bus 14",
                  "caption": "EV Charging schedule bus 14 (coordinated).",
                  "description": "Per-EV status grid (absent / charging / connected-not-charging / fully charged) over the day. Charging is staggered so the grid stays in limits while every EV still finishes."
                },
                {
                  "src": "assets/04-uncoordinated-ev-charging/03-ev-charging/station-2-bus-14/no-of-evs-charging-station-2-bus-14.png",
                  "title": "No. of EVs Charging - Station 2 (Bus 14)",
                  "caption": "No. of EVs Charging - Station 2 (Bus 14).",
                  "description": "Count of simultaneously charging EVs at this station through the day."
                }
              ],
              "children": [],
              "blocks": []
            },
            {
              "id": "4-uncoordinated-ev-charging-3-ev-charging-station-3-bus-20",
              "order": 10000.0,
              "title": "Station 3 - bus 20",
              "display": "figures",
              "figures": [
                {
                  "src": "assets/04-uncoordinated-ev-charging/03-ev-charging/station-3-bus-20/03-ev-charging-schedule-bus-20.png",
                  "title": "EV Charging schedule bus 20",
                  "caption": "EV Charging schedule bus 20 (coordinated).",
                  "description": "Per-EV status grid (absent / charging / connected-not-charging / fully charged) over the day. Charging is staggered so the grid stays in limits while every EV still finishes."
                },
                {
                  "src": "assets/04-uncoordinated-ev-charging/03-ev-charging/station-3-bus-20/no-of-evs-charging-station-3-bus-20.png",
                  "title": "No. of EVs Charging - Station 3 (Bus 20)",
                  "caption": "No. of EVs Charging - Station 3 (Bus 20).",
                  "description": "Count of simultaneously charging EVs at this station through the day."
                }
              ],
              "children": [],
              "blocks": []
            },
            {
              "id": "4-uncoordinated-ev-charging-3-ev-charging-station-4-bus-23",
              "order": 10000.0,
              "title": "Station 4 - bus 23",
              "display": "figures",
              "figures": [
                {
                  "src": "assets/04-uncoordinated-ev-charging/03-ev-charging/station-4-bus-23/04-ev-charging-schedule-bus-23.png",
                  "title": "EV Charging schedule bus 23",
                  "caption": "EV Charging schedule bus 23 (coordinated).",
                  "description": "Per-EV status grid (absent / charging / connected-not-charging / fully charged) over the day. Charging is staggered so the grid stays in limits while every EV still finishes."
                },
                {
                  "src": "assets/04-uncoordinated-ev-charging/03-ev-charging/station-4-bus-23/no-of-evs-charging-station-4-bus-23.png",
                  "title": "No. of EVs Charging - Station 4 (Bus 23)",
                  "caption": "No. of EVs Charging - Station 4 (Bus 23).",
                  "description": "Count of simultaneously charging EVs at this station through the day."
                }
              ],
              "children": [],
              "blocks": []
            },
            {
              "id": "4-uncoordinated-ev-charging-3-ev-charging-station-5-bus-26",
              "order": 10000.0,
              "title": "Station 5 - bus 26",
              "display": "figures",
              "figures": [
                {
                  "src": "assets/04-uncoordinated-ev-charging/03-ev-charging/station-5-bus-26/05-ev-charging-schedule-bus-26.png",
                  "title": "EV Charging schedule bus 26",
                  "caption": "EV Charging schedule bus 26 (coordinated).",
                  "description": "Per-EV status grid (absent / charging / connected-not-charging / fully charged) over the day. Charging is staggered so the grid stays in limits while every EV still finishes."
                },
                {
                  "src": "assets/04-uncoordinated-ev-charging/03-ev-charging/station-5-bus-26/no-of-evs-charging-station-5-bus-26.png",
                  "title": "No. of EVs Charging - Station 5 (Bus 26)",
                  "caption": "No. of EVs Charging - Station 5 (Bus 26).",
                  "description": "Count of simultaneously charging EVs at this station through the day."
                }
              ],
              "children": [],
              "blocks": []
            }
          ],
          "blocks": []
        }
      ],
      "blocks": [
        {
          "type": "info",
          "groups": [
            {
              "heading": "",
              "pairs": [
                {
                  "label": "Total EV Energy Consumption",
                  "value": "11497.75 kWh"
                },
                {
                  "label": "Total Charging Cost",
                  "value": "414108.75 LKR"
                },
                {
                  "label": "Total Energy Lost",
                  "value": "2659.73 kWh"
                }
              ]
            }
          ],
          "lines": []
        }
      ],
      "intro": "Baseline — every EV charges the moment it plugs in. The evening peak drives the far-end voltage below limit and overloads the transformer."
    },
    {
      "id": "5-coordinated-ev-charging",
      "order": 5.0,
      "title": "Coordinated EV Charging",
      "display": "figures",
      "figures": [],
      "children": [
        {
          "id": "5-coordinated-ev-charging-1-ev-charging-coordination-architecture",
          "order": 1.0,
          "title": "EV Charging Coordination Architecture",
          "display": "figures",
          "figures": [
            {
              "src": "assets/05-coordinated-ev-charging/01-ev-charging-coordination-architecture/coordination-architecture.png",
              "title": "Coordination Architecture",
              "caption": "Two-layer coordination architecture (flowchart).",
              "description": "Each 15-minute interval: update EV data, compute energy request and available EVs, run the PSO layer for the charger counts N_opt, then the Fuzzy layer to pick which EVs charge, update SOC, and repeat."
            }
          ],
          "children": [],
          "blocks": []
        },
        {
          "id": "5-coordinated-ev-charging-2-pso-layer",
          "order": 2.0,
          "title": "PSO layer",
          "display": "figures",
          "figures": [
            {
              "src": "assets/05-coordinated-ev-charging/02-pso-layer/01-pso-architecture.png",
              "title": "PSO Architecture",
              "caption": "PSO optimisation loop.",
              "description": "Particles encode the per-station charger counts (0 < Nᵢ < N_avail). Each is scored by a load flow + cost evaluation; local/global bests update until the iteration limit, returning the optimal N_opt vector."
            },
            {
              "src": "assets/05-coordinated-ev-charging/02-pso-layer/02-pso-depiction-graph.png",
              "title": "PSO depiction graph",
              "caption": "Conceptual depiction of the particle swarm search.",
              "description": "Illustrates how particles move through the decision space toward the cost-minimising charger allocation."
            }
          ],
          "children": [
            {
              "id": "5-coordinated-ev-charging-2-pso-layer-3-pso-output",
              "order": 3.0,
              "title": "PSO Output",
              "display": "tabs",
              "figures": [
                {
                  "src": "assets/05-coordinated-ev-charging/02-pso-layer/03-pso-output/pso-optimised-active-chargers-station-1-bus-6.png",
                  "title": "PSO-Optimised Active Chargers - Station 1 (Bus 6)",
                  "caption": "PSO-Optimised Active Chargers - Station 1 (Bus 6).",
                  "description": "PSO-chosen number of active chargers at this station each 15-minute interval — high during midday PV (soaking up generation) and curtailed at the evening grid peak."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/02-pso-layer/03-pso-output/pso-optimised-active-chargers-station-2-bus-14.png",
                  "title": "PSO-Optimised Active Chargers - Station 2 (Bus 14)",
                  "caption": "PSO-Optimised Active Chargers - Station 2 (Bus 14).",
                  "description": "PSO-chosen number of active chargers at this station each 15-minute interval — high during midday PV (soaking up generation) and curtailed at the evening grid peak."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/02-pso-layer/03-pso-output/pso-optimised-active-chargers-station-3-bus-20.png",
                  "title": "PSO-Optimised Active Chargers - Station 3 (Bus 20)",
                  "caption": "PSO-Optimised Active Chargers - Station 3 (Bus 20).",
                  "description": "PSO-chosen number of active chargers at this station each 15-minute interval — high during midday PV (soaking up generation) and curtailed at the evening grid peak."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/02-pso-layer/03-pso-output/pso-optimised-active-chargers-station-4-bus-23.png",
                  "title": "PSO-Optimised Active Chargers - Station 4 (Bus 23)",
                  "caption": "PSO-Optimised Active Chargers - Station 4 (Bus 23).",
                  "description": "PSO-chosen number of active chargers at this station each 15-minute interval — high during midday PV (soaking up generation) and curtailed at the evening grid peak."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/02-pso-layer/03-pso-output/pso-optimised-active-chargers-station-5-bus-26.png",
                  "title": "PSO-Optimised Active Chargers - Station 5 (Bus 26)",
                  "caption": "PSO-Optimised Active Chargers - Station 5 (Bus 26).",
                  "description": "PSO-chosen number of active chargers at this station each 15-minute interval — high during midday PV (soaking up generation) and curtailed at the evening grid peak."
                }
              ],
              "children": [],
              "blocks": []
            }
          ],
          "blocks": [
            {
              "type": "info",
              "groups": [],
              "lines": [
                "Cost Evaluation",
                "Objective Function",
                "Minimizes the power lost in the network, and",
                "the voltage fluctuations and maximizes the",
                "satisfied EV energy demand.",
                "Constraints",
                "Voltage limits, transformer loading and line",
                "loadings",
                "Decision Variable",
                "Number of Chargers at each Aggregation"
              ]
            }
          ]
        },
        {
          "id": "5-coordinated-ev-charging-3-fuzzy-layer",
          "order": 3.0,
          "title": "Fuzzy layer",
          "display": "figures",
          "figures": [
            {
              "src": "assets/05-coordinated-ev-charging/03-fuzzy-layer/01-energy-demand-input-equation.png",
              "title": "Energy Demand input equation",
              "caption": "Energy Demand input — definition.",
              "description": "The first fuzzy input: remaining energy need, normalised so urgency is comparable across vehicles of different battery sizes."
            },
            {
              "src": "assets/05-coordinated-ev-charging/03-fuzzy-layer/02-energy-demand-membership-function.png",
              "title": "Energy Demand membership function",
              "caption": "Energy Demand membership functions (Low / Medium / High).",
              "description": "Shouldered MFs — sigmoid Low and High with a bell-shaped Medium — mapping the normalised energy need onto fuzzy linguistic terms."
            },
            {
              "src": "assets/05-coordinated-ev-charging/03-fuzzy-layer/03-remaining-time-input-equation.png",
              "title": "Remaining time input equation",
              "caption": "Remaining Time input — definition.",
              "description": "The second input: intervals left before the EV departs. Less time remaining means greater urgency."
            },
            {
              "src": "assets/05-coordinated-ev-charging/03-fuzzy-layer/04-remaining-time-membership-function.png",
              "title": "Remaining time membership function",
              "caption": "Remaining Time membership functions (Low / Medium / High).",
              "description": "Maps time-to-departure onto Low/Medium/High using the same shouldered MF scheme."
            },
            {
              "src": "assets/05-coordinated-ev-charging/03-fuzzy-layer/05-fairness-index-input-equation.png",
              "title": "Fairness index input equation",
              "caption": "Fairness Index input — definition.",
              "description": "The third input: how long the EV has already waited since arrival. It prevents starvation of vehicles that keep losing the priority contest."
            },
            {
              "src": "assets/05-coordinated-ev-charging/03-fuzzy-layer/06-fairness-index-membership-function.png",
              "title": "Fairness index membership function",
              "caption": "Fairness Index membership functions (Low / Medium / High).",
              "description": "Longer waiting maps toward High, raising an EV's priority over time."
            },
            {
              "src": "assets/05-coordinated-ev-charging/03-fuzzy-layer/07-priority-score-membership-function.png",
              "title": "Priority score membership function",
              "caption": "Priority (output) membership functions.",
              "description": "The Mamdani output. After inference and defuzzification each EV gets a single priority score; the top N_opt(s) at each station are charged this interval."
            },
            {
              "src": "assets/05-coordinated-ev-charging/03-fuzzy-layer/08-control-surface-of-energy-demand-and-fairness-index-vs-priopity-score.png",
              "title": "Control surface of energy demand and fairness index vs priopity score",
              "caption": "Fuzzy control surface — Priority vs Energy Demand & Fairness.",
              "description": "The 3-D rule surface: priority rises with both energy demand and accumulated fairness, with the smooth blending produced by the 27-rule Mamdani system."
            }
          ],
          "children": [],
          "blocks": [
            {
              "type": "rulebase",
              "title": "Fuzzy IF–THEN Rule Base",
              "rules": [
                "If energy demand is high, time left is low, and fairness is any value, then the priority is high because the EV urgently needs energy and is close to departure.",
                "If energy demand is high, time left is high, and fairness is low, then the priority is low because there is sufficient time available and the EV has just arrived.",
                "If energy demand is high, time left is high, and fairness is high, then the priority is high because fairness considerations increase the priority despite available time.",
                "If energy demand is low, time left is low, and fairness is high, then the priority is medium because the EV is nearly charged but has waited for a long time.",
                "If energy demand is low, time left is any value, and fairness is low or medium, then the priority is low because the EV does not require much energy and has not waited long enough to justify higher priority."
              ]
            }
          ]
        },
        {
          "id": "5-coordinated-ev-charging-4-results",
          "order": 4.0,
          "title": "Results",
          "display": "figures",
          "figures": [],
          "children": [
            {
              "id": "5-coordinated-ev-charging-4-results-1-voltage-profile-of-each-bus",
              "order": 1.0,
              "title": "Voltage profile of each bus",
              "display": "gallery",
              "figures": [
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-1.png",
                  "title": "Bus 1",
                  "caption": "Bus 1 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 1 against the 0.94 pu lower limit. Near the substation, voltage stays close to nominal."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-2.png",
                  "title": "Bus 2",
                  "caption": "Bus 2 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 2 against the 0.94 pu lower limit. Near the substation, voltage stays close to nominal."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-3.png",
                  "title": "Bus 3",
                  "caption": "Bus 3 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 3 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-4.png",
                  "title": "Bus 4",
                  "caption": "Bus 4 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 4 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-5.png",
                  "title": "Bus 5",
                  "caption": "Bus 5 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 5 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-6.png",
                  "title": "Bus 6",
                  "caption": "Bus 6 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 6 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-7.png",
                  "title": "Bus 7",
                  "caption": "Bus 7 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 7 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-8.png",
                  "title": "Bus 8",
                  "caption": "Bus 8 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 8 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-9.png",
                  "title": "Bus 9",
                  "caption": "Bus 9 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 9 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-10.png",
                  "title": "Bus 10",
                  "caption": "Bus 10 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 10 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-11.png",
                  "title": "Bus 11",
                  "caption": "Bus 11 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 11 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-12.png",
                  "title": "Bus 12",
                  "caption": "Bus 12 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 12 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-13.png",
                  "title": "Bus 13",
                  "caption": "Bus 13 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 13 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-14.png",
                  "title": "Bus 14",
                  "caption": "Bus 14 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 14 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-15.png",
                  "title": "Bus 15",
                  "caption": "Bus 15 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 15 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-16.png",
                  "title": "Bus 16",
                  "caption": "Bus 16 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 16 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-17.png",
                  "title": "Bus 17",
                  "caption": "Bus 17 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 17 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-18.png",
                  "title": "Bus 18",
                  "caption": "Bus 18 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 18 against the 0.94 pu lower limit. Bus 18 is the critical far-end bus where the deepest sag occurs."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-19.png",
                  "title": "Bus 19",
                  "caption": "Bus 19 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 19 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-20.png",
                  "title": "Bus 20",
                  "caption": "Bus 20 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 20 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-21.png",
                  "title": "Bus 21",
                  "caption": "Bus 21 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 21 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-22.png",
                  "title": "Bus 22",
                  "caption": "Bus 22 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 22 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-23.png",
                  "title": "Bus 23",
                  "caption": "Bus 23 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 23 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-24.png",
                  "title": "Bus 24",
                  "caption": "Bus 24 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 24 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-25.png",
                  "title": "Bus 25",
                  "caption": "Bus 25 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 25 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-26.png",
                  "title": "Bus 26",
                  "caption": "Bus 26 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 26 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-27.png",
                  "title": "Bus 27",
                  "caption": "Bus 27 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 27 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-28.png",
                  "title": "Bus 28",
                  "caption": "Bus 28 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 28 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-29.png",
                  "title": "Bus 29",
                  "caption": "Bus 29 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 29 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-30.png",
                  "title": "Bus 30",
                  "caption": "Bus 30 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 30 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-31.png",
                  "title": "Bus 31",
                  "caption": "Bus 31 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 31 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-32.png",
                  "title": "Bus 32",
                  "caption": "Bus 32 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 32 against the 0.94 pu lower limit."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/01-voltage-profile-of-each-bus/bus-33.png",
                  "title": "Bus 33",
                  "caption": "Bus 33 voltage over 24 hours (coordinated).",
                  "description": "Per-unit voltage trajectory at bus 33 against the 0.94 pu lower limit."
                }
              ],
              "children": [],
              "blocks": []
            },
            {
              "id": "5-coordinated-ev-charging-4-results-2-transformer-and-line-loading",
              "order": 2.0,
              "title": "Transformer and line loading",
              "display": "figures",
              "figures": [
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/02-transformer-and-line-loading/01-transformer-loading.png",
                  "title": "Transformer loading",
                  "caption": "Transformer loading under coordination vs the 10 MVA rating.",
                  "description": "With charging staggered away from the evening peak, transformer loading stays under the 10 MVA limit — the overload of the baseline is removed."
                },
                {
                  "src": "assets/05-coordinated-ev-charging/04-results/02-transformer-and-line-loading/02-main-feeder-line-loading.png",
                  "title": "Main feeder line loading",
                  "caption": "Main feeder current under coordination vs the 525 A ampacity.",
                  "description": "Feeder current held within the cable ampacity through the night peak."
                }
              ],
              "children": [],
              "blocks": []
            },
            {
              "id": "5-coordinated-ev-charging-4-results-3-ev-charging-schedule",
              "order": 3.0,
              "title": "EV charging Schedule",
              "display": "tabs",
              "figures": [],
              "children": [
                {
                  "id": "5-coordinated-ev-charging-4-results-3-ev-charging-schedule-station-1-bus-6",
                  "order": 10000.0,
                  "title": "Station 1 - bus 6",
                  "display": "figures",
                  "figures": [
                    {
                      "src": "assets/05-coordinated-ev-charging/04-results/03-ev-charging-schedule/station-1-bus-6/01-ev-charging-schedule-bus-6.png",
                      "title": "EV Charging schedule bus 6",
                      "caption": "EV Charging schedule bus 6 (coordinated).",
                      "description": "Per-EV status grid (absent / charging / connected-not-charging / fully charged) over the day. Charging is staggered so the grid stays in limits while every EV still finishes."
                    }
                  ],
                  "children": [],
                  "blocks": []
                },
                {
                  "id": "5-coordinated-ev-charging-4-results-3-ev-charging-schedule-station-2-bus-14",
                  "order": 10000.0,
                  "title": "Station 2 - bus 14",
                  "display": "figures",
                  "figures": [
                    {
                      "src": "assets/05-coordinated-ev-charging/04-results/03-ev-charging-schedule/station-2-bus-14/02-ev-charging-schedule-bus-14.png",
                      "title": "EV Charging schedule bus 14",
                      "caption": "EV Charging schedule bus 14 (coordinated).",
                      "description": "Per-EV status grid (absent / charging / connected-not-charging / fully charged) over the day. Charging is staggered so the grid stays in limits while every EV still finishes."
                    }
                  ],
                  "children": [],
                  "blocks": []
                },
                {
                  "id": "5-coordinated-ev-charging-4-results-3-ev-charging-schedule-station-3-bus-20",
                  "order": 10000.0,
                  "title": "Station 3 - bus 20",
                  "display": "figures",
                  "figures": [
                    {
                      "src": "assets/05-coordinated-ev-charging/04-results/03-ev-charging-schedule/station-3-bus-20/03-ev-charging-schedule-bus-20.png",
                      "title": "EV Charging schedule bus 20",
                      "caption": "EV Charging schedule bus 20 (coordinated).",
                      "description": "Per-EV status grid (absent / charging / connected-not-charging / fully charged) over the day. Charging is staggered so the grid stays in limits while every EV still finishes."
                    }
                  ],
                  "children": [],
                  "blocks": []
                },
                {
                  "id": "5-coordinated-ev-charging-4-results-3-ev-charging-schedule-station-4-bus-23",
                  "order": 10000.0,
                  "title": "Station 4 - bus 23",
                  "display": "figures",
                  "figures": [
                    {
                      "src": "assets/05-coordinated-ev-charging/04-results/03-ev-charging-schedule/station-4-bus-23/04-ev-charging-schedule-bus-23.png",
                      "title": "EV Charging schedule bus 23",
                      "caption": "EV Charging schedule bus 23 (coordinated).",
                      "description": "Per-EV status grid (absent / charging / connected-not-charging / fully charged) over the day. Charging is staggered so the grid stays in limits while every EV still finishes."
                    }
                  ],
                  "children": [],
                  "blocks": []
                },
                {
                  "id": "5-coordinated-ev-charging-4-results-3-ev-charging-schedule-station-5-bus-26",
                  "order": 10000.0,
                  "title": "Station 5 - bus 26",
                  "display": "figures",
                  "figures": [
                    {
                      "src": "assets/05-coordinated-ev-charging/04-results/03-ev-charging-schedule/station-5-bus-26/05-ev-charging-schedule-bus-26.png",
                      "title": "EV Charging schedule bus 26",
                      "caption": "EV Charging schedule bus 26 (coordinated).",
                      "description": "Per-EV status grid (absent / charging / connected-not-charging / fully charged) over the day. Charging is staggered so the grid stays in limits while every EV still finishes."
                    }
                  ],
                  "children": [],
                  "blocks": []
                }
              ],
              "blocks": []
            }
          ],
          "blocks": [
            {
              "type": "info",
              "groups": [
                {
                  "heading": "",
                  "pairs": [
                    {
                      "label": "Total EV Energy Consumption",
                      "value": "11437.25 kWh"
                    },
                    {
                      "label": "Total Charging Cost",
                      "value": "365854.50 LKR"
                    },
                    {
                      "label": "Total Energy Lost",
                      "value": "2351.54 kWh"
                    }
                  ]
                }
              ],
              "lines": []
            }
          ]
        },
        {
          "id": "5-coordinated-ev-charging-5-validation",
          "order": 5.0,
          "title": "Validation",
          "display": "figures",
          "figures": [
            {
              "src": "assets/05-coordinated-ev-charging/05-validation/01-voltage-profile-of-bus-18-coordinated-vs-uncoordinated.png",
              "title": "Voltage Profile of bus 18 - Coordinated Vs Uncoordinated",
              "caption": "Bus 18 voltage — coordinated vs uncoordinated.",
              "description": "The critical far-end bus. The uncoordinated case dips to ~0.928 pu in the evening (below the 0.94 limit); coordination holds it at the 0.94 boundary throughout."
            },
            {
              "src": "assets/05-coordinated-ev-charging/05-validation/02-transformer-loading-coordinated-vs-uncoordinated.png",
              "title": "Transformer Loading - Coordinated Vs Uncoordinated",
              "caption": "Transformer loading — coordinated vs uncoordinated.",
              "description": "Side-by-side loading. The baseline breaches 10 MVA at the peak; the coordinated trace stays beneath it."
            },
            {
              "src": "assets/05-coordinated-ev-charging/05-validation/03-main-feeder-current-coordinated-vs-uncoordinated.png",
              "title": "Main feeder current - Coordinated vs Uncoordinated",
              "caption": "Main feeder current — coordinated vs uncoordinated.",
              "description": "Coordination shaves the night-peak feeder current relative to the baseline."
            },
            {
              "src": "assets/05-coordinated-ev-charging/05-validation/04-remaining-total-energy-demand.png",
              "title": "Remaining Total Energy Demand",
              "caption": "Remaining total EV energy demand over the day.",
              "description": "Backlog of undelivered energy across the fleet. Both cases drive demand to (near) zero by departure — coordination meets the same needs, just spread intelligently in time."
            },
            {
              "src": "assets/05-coordinated-ev-charging/05-validation/05-voltage-stability-index-coordinated-vs-uncoordinated.png",
              "title": "Voltage Stability Index Coordinated vs uncoordinated",
              "caption": "Worst-case Voltage Stability Index per bus.",
              "description": "VSI (min) for every bus. The coordinated curve sits above the uncoordinated one across the feeder — notably at the far buses — confirming improved stability margins."
            }
          ],
          "children": [],
          "blocks": [
            {
              "type": "info",
              "groups": [
                {
                  "heading": "Uncoordinated case",
                  "pairs": [
                    {
                      "label": "Total EV Energy Consumption",
                      "value": "11497.75 kWh"
                    },
                    {
                      "label": "Total Charging Cost",
                      "value": "414108.75 LKR"
                    },
                    {
                      "label": "Total Energy Lost",
                      "value": "2659.73 kWh"
                    }
                  ]
                },
                {
                  "heading": "Coordinated Case",
                  "pairs": [
                    {
                      "label": "Total EV Energy Consumption",
                      "value": "11437.25 kWh"
                    },
                    {
                      "label": "Total Charging Cost",
                      "value": "365854.50 LKR"
                    },
                    {
                      "label": "Total Energy Lost",
                      "value": "2351.54 kWh"
                    }
                  ]
                }
              ],
              "lines": [],
              "comparison": {
                "columns": [
                  "Uncoordinated case",
                  "Coordinated Case"
                ],
                "metrics": [
                  {
                    "label": "Total EV Energy Consumption",
                    "values": [
                      "11497.75 kWh",
                      "11437.25 kWh"
                    ]
                  },
                  {
                    "label": "Total Charging Cost",
                    "values": [
                      "414108.75 LKR",
                      "365854.50 LKR"
                    ]
                  },
                  {
                    "label": "Total Energy Lost",
                    "values": [
                      "2659.73 kWh",
                      "2351.54 kWh"
                    ]
                  }
                ]
              }
            }
          ]
        }
      ],
      "blocks": [],
      "intro": "The proposed strategy — a hierarchical PSO (how many chargers) + Fuzzy (which EVs) controller that keeps the grid stable while still meeting demand."
    }
  ]
};
